[package]
name = "auto-re"
version = "0.1.0"
edition = "2024"

[lib]
name = "auto-re"
path = "src/lib.rs"

[[bin]]
name = "auto-re"
path = "src/main.rs"

[dependencies]
thiserror = "2.0.18"
async-openai = "0.32.3"
idalib = "0.7"

[build-dependencies]
idalib-build = "0.7"
